services:

# WIP: getting connection refused in NGINX logs when trying to route to localhost:8080/1 (Toxiproxy)
#  toxiproxy:
#    image: ghcr.io/shopify/toxiproxy
#    command:
#      - -host=0.0.0.0
#      - -proxy-metrics
#      - -config=/config/toxiproxy.json
#    volumes:
#      - ./toxiproxy/toxiproxy.json:/config/toxiproxy.json
#    ports:
#      - "8474:8474"
#      - "8080:8080"
#      - "8081:8081"

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wiremock_a
      - wiremock_b

  wiremock_a:
    image: wiremock/wiremock
    volumes:
      - ./wiremock/mappings/hello:/home/wiremock/mappings

  wiremock_b:
    image: wiremock/wiremock
    command: "--port 8081"
    volumes:
      - ./wiremock/mappings/goodbye:/home/wiremock/mappings

